### ISSUE TITLE
[request] Hide day \ night button.

### ISSUE THREAD

**Issue by vasecha** [gashole/TimeManager#1]
Hi! I love this addon. 
Is there a way to hide day \ night button and call addon frame by the clicking on clock? It would be just amazing if so. 
Thank You in advance!

**Comment by gashole** [comment]
You can hide the Day/Night indicator by adding `GameTimeFrame:Hide()` to a AddOn's .lua file. If hidden, the Clock button is used to access the Clock UI.

**Comment by gashole** [comment]
You can hide the Day/Night indicator by adding GameTimeFrame:Hide() to an AddOn's .lua file. If hidden, the Clock button is used to access the Clock UI.

**Comment by gashole** [comment]
You can hide the Day/Night indicator by adding `GameTimeFrame:Hide()` to an AddOn's .lua file. If hidden, the Clock button is used to access the Clock UI.

**Comment by vasecha** [comment]
Done. :) 
Thank you!
